version: '3.1'

services:
  api:
    build: ./Mini_Projet_1
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: gotham_dev
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - api-tier
      - vue-tier
    tty: true
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: gotham_dev
      PGPORT: 5432
      PGHOST: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - api-tier

  vue:
    build: ./Mini_Projet_2/router-app
    ports:
      - "5000:80"
    networks:
      - vue-tier

networks:
  vue-tier:

  api-tier:

volumes:
  db-data: