version: '3.1'

services:
  
  db:
    build: ./Mini_Projet_3
    expose:
      - 5432
    networks:
      - api-tier
    ports:
      - "5432:5432"
  api:
      build: ./Mini_Projet_1
      environment:
        PGUSER: postgres
        PGPASSWORD: postgres
        PGDATABASE: gotham_dev
        PGPORT: 5432
        PGHOST: db
      container_name: "api"
      ports:
        - "4000:4000"
      depends_on:
        - db
      networks:
        - api-tier
      tty: true
  vue:
    build: ./Mini_Projet_2/router-app
    ports:
      - "5000:80"
    networks:
      - vue-tier

networks:
  vue-tier:

  api-tier:

volumes:
  data: {}